# .github/workflows/windows.yml
name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            msystem: MINGW64
            pkg_prefix: mingw-w64-x86_64
          - architecture: aarch64
            msystem: MINGW64
            pkg_prefix: mingw-w64-x86_64
            extra_cmake_args: -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_FLAGS="-target aarch64-w64-mingw32 -fuse-ld=lld" -DCMAKE_C_FLAGS="-target aarch64-w64-mingw32 -fuse-ld=lld" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=ARM64 -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY -DBUILD_SHARED_LIBS=OFF

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v6
        with:
          clean: true
          lfs: true

      - name: Install Toolchain on Windows
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          path-type: inherit
          install: >-
            ${{ matrix.pkg_prefix }}-toolchain
            ${{ matrix.pkg_prefix }}-clang
          cache: true
        timeout-minutes: 90

      - name: Configure CMake on Windows
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles" ${{ matrix.extra_cmake_args }}

      - name: Build
        run: |
          cmake --build build --config ${{env.BUILD_TYPE}} -j $(nproc)

      - name: List build directory contents on Windows
        run: |
          echo "Build directory contents:"
          ls -R build/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: duckshell-windows-${{ matrix.architecture }}-${{ env.BUILD_TYPE }}
          path: build/DuckShell.exe
          if-no-files-found: warn

      - name: Clean cache on Windows
        run: rm -rf build
