# .github/workflows/windows.yml
name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            msystem: MINGW64
            pkg_prefix: mingw-w64-x86_64
            extra_cmake_args: "-G \"MinGW Makefiles\""
            shell: msys2 {0}
          - architecture: aarch64
            msystem: MSVC
            pkg_prefix: ""
            extra_cmake_args: "-G \"Visual Studio 17 2022\" -A ARM64"
            shell: powershell

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - uses: actions/checkout@v6
        with:
          clean: true
          lfs: true

      - name: Install Toolchain on Windows
        if: matrix.msystem != 'MSVC'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          path-type: inherit
          install: >-
            ${{ matrix.pkg_prefix }}-toolchain
          cache: true
        timeout-minutes: 90

      - name: Install x64 Make for ARM64 build
        if: matrix.architecture == 'aarch64'
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-make

      - name: Configure CMake on Windows
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{ matrix.extra_cmake_args }}

      - name: Build
        run: |
          cmake --build build --config ${{env.BUILD_TYPE}}

      - name: List build directory contents on Windows
        run: |
          echo "Build directory contents:"
          ls build/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: duckshell-windows-${{ matrix.architecture }}-${{ env.BUILD_TYPE }}
          path: |
            build/DuckShell.exe
            build/Release/DuckShell.exe
          if-no-files-found: warn

      - name: Clean cache on Windows
        run: rm -rf build
