# .github/workflows/windows.yml
name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            msystem: MINGW64
            pkg_prefix: mingw-w64-x86_64
          - architecture: aarch64
            msystem: CLANGARM64
            pkg_prefix: mingw-w64-clang-aarch64

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v6
        with:
          clean: true

      - name: Install Toolchain on Windows
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.pkg_prefix }}-toolchain
            ${{ matrix.pkg_prefix }}-cmake
          cache: true
        timeout-minutes: 90

      - name: Configure CMake on Windows
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles"

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j $(nproc)

      - name: List build directory contents on Windows
        run: |
          echo "Build directory contents:"
          ls -R build/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: duckshell-windows-${{ matrix.architecture }}-${{ env.BUILD_TYPE }}
          path: build/DuckShell.exe
          if-no-files-found: warn

      - name: Clean cache on Windows
        run: rm -rf build
